version: "3.3"

services:
  mina:
    image: ${MINA}
    container_name: mina
    ports:
      - "6060:6060"
      - "8302:8302"
      - "127.0.0.1:3085:3085"
    restart: always
    env_file:
      - $HOME/mina-bp-setup/.env
    environment: 
      MINA_PRIVKEY_PASS: ${MINA_PRIVKEY_PASS}
      CODA_PRIVKEY_PASS: ${CODA_PRIVKEY_PASS}
      UPTIME_PRIVKEY_PASS: ${UPTIME_PRIVKEY_PASS}
      KEYPATH: ${KEYPATH}
      COINBASE_RECEIVER: ${COINBASE_RECEIVER}
    volumes:
      - "$HOME/.mina-config:/root/.mina-config"
      - "$HOME/keys:/root/keys:ro"
      - "./import.sh:/entrypoint.d/import.sh"
    command: >
      daemon
        --peer-list-url ${PEER_LIST}
        --block-producer-key ${KEYPATH}
        --coinbase-receiver ${COINBASE_RECEIVER}
        --uptime-submitter-key ${KEYPATH}
        --uptime-url ${UPTIME_URL}
        ${NODE_STATUS_URL}
        ${NODE_ERROR_URL}
        --metrics-port 6060
        --open-limited-graphql-port
        --limited-graphql-port 3095
        --insecure-rest-server
        --file-log-level Debug
        --log-level Info
        ${STOP_TIME}
    networks:
      - mina 

  sidecar:
    image: ${SIDECAR}
    container_name: sidecar
    depends_on:
      - mina
    pid: host
    restart: always
    env_file:
      - $HOME/mina-bp-setup/.env
    volumes:
      - "$HOME/mina-bp-setup/sidecar.json:/etc/mina-sidecar.json"
    networks:
      - mina
          
networks:
  mina:
    driver: bridge
